<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Account' => 'Profil',
  'Administration' => 'Administration',
  'Best Regards' => 'Beste Grüße',
  'Change Password' => 'Passwort ändern',
  'Change your Password' => 'Passwort ändern',
  'Data successfully changed!' => 'Daten geändert!',
  'Dear Sir or Madam!' => 'Sehr geehrte Damen und Herren, ',
  'Don´t forget to change your password after next login!' => 'Bitte vergessen Sie nicht, Ihr Passwort beim nächsten Login zu ändern',
  'Edit Account' => 'Profil bearbeiten',
  'Edit Profile' => 'Profil bearbeiten',
  'Edit your profile' => 'Profil bearbeiten',
  'Home' => 'Home',
  'I forgot my password' => 'Passwort vergessen',
  'Is a administrator' => 'Ist ein Admin',
  'Join Game' => 'Spiel beitreten',
  'Join to a additional game' => 'Einem weiteren Spiel beitreten',
  'Mail' => 'E-Mail',
  'Name' => 'Name',
  'No permissions to use this game!' => 'Sie haben keine Berechtigung diesem Spiel beizutreten!',
  'No user found with this e-mail address!' => 'Kein Nutzer mit dieser E-Mailadresse gefunden!',
  'Password successfully changed!' => 'Passwort erfolgreich geändert!',
  'Password successfully resetted!' => 'Passwort erfolgreich zurückgesetzt!',
  'Reset Password' => 'Passwort zurücksetzen',
  'Reset password for SCSIM' => 'Passwort zurücksetzen',
  'Settings' => 'Einstellungen',
  'Subject' => 'Betreff',
  'Successfully joined the game!' => 'Spiel erfolgreich beigetreten!',
  'There are no groups in the current game!' => 'Keine Gruppen im Spiel angelegt!',
  'This is your new Password: "{password}"' => 'Ihr neues Passwort: "{password}"',
  'User' => 'Benutzer',
  'Wow! You get a mail from a SCSIM player:' => 'Sie haben eine Nachricht einen SCSIM-Spielers erhalten:',
  'You are already in this game!' => 'Sie sind bereits Mitglied in diesem Spiel!',
  'You have been inactive by an admin.' => 'Sie wurden druch den Administrator gesperrt!',
  'Your SCSIM Team' => 'Ihr SCSIM Team',
  'here is your new random password:' => 'Ihr neues Zufallspasswort:',
  'Blocked' => 'Blockiert',
  'Choose Game' => 'Spiel wählen',
  'Choose Group' => 'Gruppe wählen',
  'Choose current game:' => 'Spiel wählen!',
  'Created' => 'Erstellt',
  'Email' => 'E-Mail',
  'Gamekey' => 'Gamekey',
  'Gamekey not valid!' => 'Gamekey ist ungültig!',
  'Group is full' => 'Gruppe ist voll',
  'Group is full!' => 'Gruppe ist voll!',
  'Group:' => 'Gruppe:',
  'Ident' => 'Matrikelnummer',
  'Internal error!' => 'Interner Fehler',
  'Join now!' => 'Beitreten',
  'Lastname' => 'Nachname',
  'Login' => 'Login',
  'Login on SCSIM' => 'Einloggen bei SCSIM',
  'Logout' => 'Logout',
  'Old password' => 'Altes Passwort',
  'Organisation' => 'Organisation',
  'Password' => 'Passwort',
  'Password Crypted' => 'Passwort Crypted',
  'Password repeat' => 'Passwort wiederholen',
  'Please ask your trainer for this!' => 'Bitte fragen Sie Ihren Dozenten!',
  'Please check the errors below!' => 'Es wurden Eingabefehler festgestellt!',
  'Please select a language:' => 'Sprache wählen:',
  'Prename' => 'Vorname',
  'Problem while saving!' => 'Problem während des Speichervorgangs!',
  'Register' => 'Registrieren',
  'Register for SCSIM' => 'Für SCSIM registrieren',
  'Registration successfull! Please check your mails for further instructions!' => 'Registrierung erfolgreich! Bitte prüfen Sie Ihre E-Mails!',
  'Remember me next time' => 'Eingeloggt bleiben',
  'Reset' => 'Zurücksetzen',
  'You are already member of another group!' => 'Sie sind bereits einer anderen Gruppe beigetreten!',
  'You have joined the chosen group!' => 'Sie sind jetzt Mitglied in der Gruppe',
  'You will get your key from your trainer!' => 'Der Gamekey wird vom Dozenten ausgegeben!',
  'no member of a group' => 'Kein Mitglied einer Gruppe',
  'use this' => 'verwenden',
  '{usercount} of {usermax} members are in the group' => '{usercount} von {usermax} Mitglieder in dieser Gruppe',
);
