<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Account' => '',
  'Administration' => '',
  'Best Regards' => '',
  'Blocked' => '',
  'Change Password' => '',
  'Change your Password' => '',
  'Choose Game' => '',
  'Choose Group' => '',
  'Choose current game:' => '',
  'Created' => '',
  'Data successfully changed!' => '',
  'Dear Sir or Madam!' => '',
  'Don´t forget to change your password after next login!' => '',
  'Edit Account' => '',
  'Edit Profile' => '',
  'Edit your profile' => '',
  'Email' => '',
  'Gamekey' => '',
  'Gamekey not valid!' => '',
  'Group is full' => '',
  'Group is full!' => '',
  'Group:' => '',
  'Home' => '',
  'I forgot my password' => '',
  'Ident' => '',
  'Internal error!' => '',
  'Is a administrator' => '',
  'Join Game' => '',
  'Join now!' => '',
  'Join to a additional game' => '',
  'Lastname' => '',
  'Login' => '',
  'Login on SCSIM' => '',
  'Logout' => '',
  'Mail' => '',
  'Name' => '',
  'No permissions to use this game!' => '',
  'No user found with this e-mail address!' => '',
  'Old password' => '',
  'Organisation' => '',
  'Password' => '',
  'Password Crypted' => '',
  'Password repeat' => '',
  'Password successfully changed!' => '',
  'Password successfully resetted!' => '',
  'Please ask your trainer for this!' => '',
  'Please check the errors below!' => '',
  'Please select a language:' => '',
  'Prename' => '',
  'Problem while saving!' => '',
  'Register' => '',
  'Register for SCSIM' => '',
  'Registration successfull! Please check your mails for further instructions!' => '',
  'Remember me next time' => '',
  'Reset' => '',
  'Reset Password' => '',
  'Reset password for SCSIM' => '',
  'Settings' => '',
  'Subject' => '',
  'Successfully joined the game!' => '',
  'There are no groups in the current game!' => '',
  'This is your new Password: "{password}"' => '',
  'User' => '',
  'Wow! You get a mail from a SCSIM player:' => '',
  'You are already in this game!' => '',
  'You are already member of another group!' => '',
  'You have been inactive by an admin.' => '',
  'You have joined the chosen group!' => '',
  'You will get your key from your trainer!' => '',
  'Your SCSIM Team' => '',
  'here is your new random password:' => '',
  'no member of a group' => '',
  'use this' => '',
  '{usercount} of {usermax} members are in the group' => '',
);
